/* Phase 2 data: full profiles. Famous names are well-known public figures. */
const PROFILES = {
aries:{str:"Brave, direct, energetic",chal:"Impatient, hot-tempered, hates coming second",love:"Passionate and upfront. Loves the chase and says what they feel.",friend:"Loyal and fun. First to show up and first to defend you.",career:"Thrives at leading, competing and starting things from scratch.",talk:"Short, frank and fast. No hints, just the point.",likes:"Challenges, competition, fresh starts",dislikes:"Waiting, routine, being told what to do",assoc:"Red, diamond, Tuesday",myth:"Linked to the golden ram whose fleece Jason and the Argonauts sought.",fam:"Lady Gaga, Robert Downey Jr., Leonardo da Vinci"},
taurus:{str:"Reliable, patient, grounded",chal:"Stubborn, possessive, slow to change",love:"Devoted and sensual. Shows love through steady presence and small comforts.",friend:"Dependable and generous with time, food and loyalty.",career:"Strong in finance, craft and design, anything that rewards patience.",talk:"Calm and deliberate. Thinks first, then sticks to it.",likes:"Good food, comfort, stability",dislikes:"Rushing, sudden change, being pushed",assoc:"Green, emerald, Friday",myth:"Often tied to Zeus, who took the form of a white bull to carry Europa across the sea.",fam:"Adele, Dwayne Johnson, Queen Elizabeth II"},
gemini:{str:"Curious, witty, adaptable",chal:"Restless, inconsistent, easily bored",love:"Needs a partner who can talk for hours and keep surprising them.",friend:"Sociable and funny, with friends in many circles.",career:"Suited to writing, media, sales, teaching and quick-moving work.",talk:"Quick and playful. Loves banter, questions and new ideas.",likes:"Conversation, novelty, learning",dislikes:"Boredom, being tied down, long silences",assoc:"Yellow, agate, Wednesday",myth:"The twins Castor and Pollux, inseparable brothers placed among the stars.",fam:"Marilyn Monroe, Tupac Shakur, Naomi Campbell"},
cancer:{str:"Caring, intuitive, protective",chal:"Moody, guarded, clingy when hurt",love:"Tender and devoted. Wants a safe, close bond and builds a home around it.",friend:"Remembers everything about you and shows up when it counts.",career:"Does well in care, teaching, hospitality and family business.",talk:"Gentle and indirect. Speaks through feeling more than logic.",likes:"Home, family, old memories",dislikes:"Criticism, feeling unwelcome, cold people",assoc:"Silver, pearl, Monday",myth:"The crab Hera sent to pinch Heracles during his fight with the Hydra.",fam:"Ariana Grande, Tom Hanks, Burna Boy"},
leo:{str:"Generous, confident, creative",chal:"Proud, dramatic, needs to be noticed",love:"Warm and loyal. Loves grand gestures and wants to be admired in return.",friend:"A big-hearted host who makes everyone feel included.",career:"Natural at leading, performing, creating and promoting.",talk:"Expressive and confident. Tells a story well and likes an audience.",likes:"The spotlight, praise, celebration",dislikes:"Being ignored, pettiness, being laughed at",assoc:"Gold, ruby, Sunday",myth:"The Nemean Lion, whose hide no weapon could pierce until Heracles strangled it.",fam:"Jennifer Lopez, Barack Obama, Madonna"},
virgo:{str:"Careful, practical, helpful",chal:"Critical, anxious, hard on themselves",love:"Shows love through acts of service and quiet attention to detail.",friend:"The one who remembers, fixes and gives honest advice.",career:"Excels at analysis, health, editing, research and organising.",talk:"Precise and thoughtful. Prefers facts to drama.",likes:"Order, routine, being useful",dislikes:"Mess, carelessness, loud show-offs",assoc:"Brown, sapphire, Wednesday",myth:"Often linked to Demeter or Astraea, goddesses of harvest and justice.",fam:"Beyoncé, Keanu Reeves, Zendaya"},
libra:{str:"Fair, charming, diplomatic",chal:"Indecisive, avoids conflict, people-pleasing",love:"Romantic and devoted. Wants partnership, harmony and shared beauty.",friend:"Easy company who keeps the peace and brings people together.",career:"Fits law, design, mediation, diplomacy and other people-facing roles.",talk:"Polite and balanced. Hears both sides before giving an opinion.",likes:"Beauty, fairness, good company",dislikes:"Conflict, rudeness, being alone",assoc:"Pink, opal, Friday",myth:"The scales of justice, the only sign shown as an object rather than a living thing.",fam:"Will Smith, Kim Kardashian, Mahatma Gandhi"},
scorpio:{str:"Determined, loyal, perceptive",chal:"Jealous, secretive, holds grudges",love:"All in or not at all. Bonds deeply and expects the same honesty.",friend:"Few friends, fiercely loyal, and a keeper of secrets.",career:"Strong in research, investigation, strategy and crisis work.",talk:"Measured and intense. Says less, means more.",likes:"Privacy, depth, mystery",dislikes:"Dishonesty, shallow talk, being exposed",assoc:"Deep red, topaz, Tuesday",myth:"The scorpion sent to sting the hunter Orion, then set in the sky opposite him.",fam:"Leonardo DiCaprio, Bill Gates, Davido"},
sagittarius:{str:"Optimistic, honest, adventurous",chal:"Blunt, restless, avoids commitment",love:"Wants a partner who is also a travel companion and best friend.",friend:"Fun, frank and always up for a plan.",career:"Drawn to travel, teaching, publishing, sport and entrepreneurship.",talk:"Open and enthusiastic. Honest even when it stings.",likes:"Travel, freedom, big ideas",dislikes:"Being restricted, clingy people, pointless rules",assoc:"Purple, turquoise, Thursday",myth:"A centaur archer, often linked to the wise teacher Chiron.",fam:"Taylor Swift, Jay-Z, Brad Pitt"},
capricorn:{str:"Disciplined, responsible, patient",chal:"Too serious, workaholic, slow to open up",love:"Slow to trust, then loyal for the long run.",friend:"Steady and dependable. Shows care by helping.",career:"Built for management, finance, engineering and long careers.",talk:"Reserved and practical. Dry humour, few wasted words.",likes:"Goals, tradition, results",dislikes:"Laziness, waste, being rushed",assoc:"Brown, garnet, Saturday",myth:"The sea-goat, tied to Pan, who dived into a river and grew a fish's tail.",fam:"Denzel Washington, Michelle Obama, Elvis Presley"},
aquarius:{str:"Original, independent, humane",chal:"Detached, stubborn, unpredictable",love:"Wants friendship first and plenty of room to stay themselves.",friend:"Loyal to ideas and people, with friends from everywhere.",career:"Suited to tech, science, activism and inventive work.",talk:"Clever and unconventional. Likes debating big ideas.",likes:"New ideas, causes, freedom",dislikes:"Rules for their own sake, clinginess, being boxed in",assoc:"Electric blue, amethyst, Saturday",myth:"The water-bearer, linked to Ganymede, the cup-bearer of the gods.",fam:"Cristiano Ronaldo, Oprah Winfrey, Tiwa Savage"},
pisces:{str:"Empathetic, imaginative, gentle",chal:"Escapist, oversensitive, unsure of boundaries",love:"Romantic and selfless. Loves deeply and dreams big about it.",friend:"A gentle listener who picks up on moods.",career:"Drawn to art, music, healing, film and caring work.",talk:"Soft and poetic. Speaks in feelings and images.",likes:"Music, dreams, quiet time",dislikes:"Cruelty, harsh noise, cold logic",assoc:"Sea green, aquamarine, Thursday",myth:"Two fish tied together, said to be Aphrodite and Eros escaping the monster Typhon.",fam:"Rihanna, Albert Einstein, Steve Jobs"}
};

const SYM = {aries:"Ram",taurus:"Bull",gemini:"Twins",cancer:"Crab",leo:"Lion",virgo:"Maiden",libra:"Scales",scorpio:"Scorpion",sagittarius:"Archer",capricorn:"Sea-goat",aquarius:"Water-bearer",pisces:"Two fish"};
const PERS = {
aries:"Aries moves first and thinks out loud. They are competitive, generous with their energy, and quick to forgive.",
taurus:"Taurus is calm, loyal and hard to rush. They enjoy beauty and comfort, and once they decide, they rarely change course.",
gemini:"Gemini is curious, talkative and quick to see the funny side. Their mind is always on the next idea, which makes them good company and hard to pin down.",
cancer:"Cancer feels deeply and protects their people. They can seem shy at first, then turn out to be the warmest person in the room.",
leo:"Leo is warm, proud and generous. They light up a room and want the people they love to shine too.",
virgo:"Virgo is thoughtful, observant and quietly capable. They notice what needs doing and usually just do it.",
libra:"Libra is gracious, fair-minded and drawn to harmony. They want everyone to feel heard, even when that makes deciding slow.",
scorpio:"Scorpio is intense, private and loyal. They look beneath the surface and expect others to be real with them.",
sagittarius:"Sagittarius is curious, upbeat and frank. They need room to roam, in ideas as much as in places.",
capricorn:"Capricorn is patient, serious and driven. They build slowly, keep their word, and show a dry sense of humour once they trust you.",
aquarius:"Aquarius is original, independent and a little unpredictable. They care about people and ideas, and prefer to do things their own way.",
pisces:"Pisces is gentle, dreamy and deeply empathetic. They pick up on how others feel and often express it through art or music."
};
for (const k in PERS) PROFILES[k].pers = PERS[k];